<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>InformationDetail-Failed</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>209d62ef-133f-4842-a5ae-a3c3e30170d0</testSuiteGuid>
   <testCaseLink>
      <guid>526b7acb-c231-4db0-b1b9-705e1ddb12df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Information-Detail/InformationDetail-VariantNull</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ab9e4d9b-5e00-4732-971b-0b4c2bf2bd34</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dataInformation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ab9e4d9b-5e00-4732-971b-0b4c2bf2bd34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>235b6e9e-3b6c-4c14-9aba-bf8bfa4576dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ab9e4d9b-5e00-4732-971b-0b4c2bf2bd34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>425797a8-6b30-46fb-9cf8-f7c2963bfa6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ab9e4d9b-5e00-4732-971b-0b4c2bf2bd34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Phone</value>
         <variableId>6f88f480-9986-4e65-948a-e3b171f16436</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ab9e4d9b-5e00-4732-971b-0b4c2bf2bd34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company</value>
         <variableId>9f7a1382-0c56-4d65-8b0e-3cf99c5cfeb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0967db77-5cdc-45d1-ad64-0eb7e1557d92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Information-Detail/InformationDetail-EmailNotValid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b0413975-5a7a-475c-9759-cba77a9be953</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Information-Detail/InformationDetail-PhoneNotValid</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
